### PR TITLE
Update and rename ModbusSlave.h to ModbusSlave.h1

### PR DESCRIPTION
**Pull request by behroz123**

### CODE REVIEW

**Comment by yaacov** [comment]
why ?

**Comment by behroz123** [comment]
hi want with serial2 modbus creation
witch part edite?

tanks

**Comment by yaacov** [comment]
> want with serial2 modbus creation witch part edite?

if you want to use Serial1 or [SoftwareSerial](https://www.arduino.cc/en/Tutoria/SoftwareSerialExample) you do not need to change the library, you can use the [constractor](https://github.com/yaacov/ArduinoModbusSlave/blob/master/src/ModbusSlave.cpp#L37) that takes the serial port as first argument.

Example:

```
Modbus slave(Serial1, SLAVE_ID, CTRL_PIN);
...
Serial1.begin( BAUDRATE );
slave.begin( BAUDRATE );
```

Is this what you want to achieve ?

**Comment by behroz123** [comment]
yes ,Please library send me
if you have telegram Please id send me
thanks

**Comment by yaacov** [comment]
> yes

?

can we close this request ?
I do not understand what you write :-(

**Comment by behroz123** [comment]
ok
thanks

**Comment by behroz123** [comment]
Arduino: 1.8.4 (Windows 8.1), Board: "Arduino/Genuino Mega or Mega 2560,
ATmega2560 (Mega 2560)"

C:\Users\behrouz\Documents\Arduino\sketch_oct05a\sketch_oct05a.ino: In
function 'void setup()':

sketch_oct05a:50: error: 'Modbus' was not declared in this scope

   Modbus slave(Serial1, SLAVE_ID, CTRL_PIN);

   ^

sketch_oct05a:52: error: 'class modbusSlave' has no member named 'begin'

   slave.begin( 9600 );

         ^

exit status 1
'Modbus' was not declared in this scope

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.




#include <modbus.h>
#include <modbusDevice.h>
#include <modbusRegBank.h>
#include <modbusSlave.h>

/* PINS
Add more registers if needed
Digital input pins 2,3,4,5,6,7
Digital output pins 8,9,12,13
Analog output pins 10,11 (PWM)
Analog input pins 0,1,2,3,4,5
*/


modbusDevice regBank;
modbusSlave slave;

int AI0,AI1,AI2,AI3,AI4,AI5;


void setup()
{
  regBank.setId(1); ///Set Slave ID

//Add Digital Input registers
  regBank.add(10002);
  regBank.add(10003);
  regBank.add(10004);
  regBank.add(10005);
  regBank.add(10006);
  regBank.add(10007);
// Add Digital Output registers
  regBank.add(8);
  regBank.add(9);
  regBank.add(12);
  regBank.add(13);
//Analog input registers
  regBank.add(30001);
  regBank.add(30002);
  regBank.add(30003);
  regBank.add(30004);
  regBank.add(30005);
  regBank.add(30006);
//Analog Output registers
  regBank.add(40010);
  regBank.add(40011);

  slave._device = &regBank;
  slave.setBaud(9600);
  Modbus slave(Serial1, SLAVE_ID, CTRL_PIN);
  Serial1.begin( 9600 );
  slave.begin( 9600 );

  pinMode(2,INPUT);
  pinMode(3,INPUT);
  pinMode(4,INPUT);
  pinMode(5,INPUT);
  pinMode(6,INPUT);
  pinMode(7,INPUT);
  pinMode(8,OUTPUT);
  pinMode(9,OUTPUT);
  pinMode(12,OUTPUT);
  pinMode(13,OUTPUT);

}
void loop(){

  while(1){
  //Digital Input
    byte DI2 = digitalRead(2);
    if (DI2 >= 1)regBank.set(10002,1);
    if (DI2 <= 0)regBank.set(10002,0);
    byte DI3 = digitalRead(3);
    if (DI3 >= 1)regBank.set(10003,1);
    if (DI3 <= 0)regBank.set(10003,0);
    byte DI4 = digitalRead(4);
    if (DI4 >= 1)regBank.set(10004,1);
    if (DI4 <= 0)regBank.set(10004,0);
    byte DI5 = digitalRead(5);
    if (DI5 >= 1)regBank.set(10005,1);
    if (DI5 <= 0)regBank.set(10005,0);
    byte DI6 = digitalRead(6);
    if (DI6 >= 1)regBank.set(10006,1);
    if (DI6 <= 0)regBank.set(10006,0);
    byte DI7 = digitalRead(7);
    if (DI7 >= 1)regBank.set(10007,1);
    if (DI7 <= 0)regBank.set(10007,0);

  //Digital output
    int DO8 = regBank.get(8);
      if (DO8 <= 0 && digitalRead(8) == HIGH)digitalWrite(8,LOW);
      if (DO8 >= 1 && digitalRead(8) == LOW)digitalWrite(8,HIGH);
    int DO9 = regBank.get(9);
      if (DO9 <= 0 && digitalRead(9) == HIGH)digitalWrite(9,LOW);
      if (DO9 >= 1 && digitalRead(9) == LOW)digitalWrite(9,HIGH);
    int DO12 = regBank.get(12);
      if (DO12 <= 0 && digitalRead(12) == HIGH)digitalWrite(12,LOW);
      if (DO12 >= 1 && digitalRead(12) == LOW)digitalWrite(12,HIGH);
    int DO13 = regBank.get(13);
      if (DO13 <= 0 && digitalRead(13) == HIGH)digitalWrite(13,LOW);
      if (DO13 >= 1 && digitalRead(13) == LOW)digitalWrite(13,HIGH);

  //Analog input  ***READ Twice deliberately
    AI0 = analogRead(0);
    delay(10);
    AI0 = analogRead(0);
    regBank.set(30001, (word) AI0);
    delay(10);

    AI1 = analogRead(1);
    delay(10);
    AI1 = analogRead(1);
    regBank.set(30002, (word) AI1);
    delay(10);

    AI2 = analogRead(2);
    delay(10);
    AI2 = analogRead(2);
    regBank.set(30003, (word) AI2);
    delay(10);

    AI3 = analogRead(3);
    delay(10);
    AI3 = analogRead(3);
    regBank.set(30004, (word) AI3);
    delay(10);

    AI4 = analogRead(4);
    delay(10);
    AI4 = analogRead(4);
    regBank.set(30005, (word) AI4);
    delay(10);

    AI5 = analogRead(5);
    delay(10);
    AI5 = analogRead(5);
    regBank.set(30006, (word) AI5);
    delay(10);

  //Analog output
    word AO10 = regBank.get(40010);
    analogWrite(10,AO10);
    delay(10);
    word AO11 = regBank.get(40011);
    analogWrite(11,AO11);
    delay(10);

  slave.run();
  }
}

**Comment by behroz123** [comment]
error!

**Comment by yaacov** [comment]
> exit status 1 'Modbus' was not declared in this scope

'Modbus' is declared here: https://github.com/yaacov/ArduinoModbusSlave/blob/master/src/ModbusSlave.h

Find why it is missing in your setup.

**Comment by yaacov** [comment]
```
slave.setBaud(9600); 
Modbus slave(Serial1, SLAVE_ID, CTRL_PIN);
```
you can not use `slave` before declaring it 

```
slave._device = &regBank;
```
you can not do that.

see example: https://github.com/yaacov/ArduinoModbusSlave/blob/master/examples/simple/simple.ino

**Comment by yaacov** [comment]
> #include <modbusRegBank.h>

are you trying to mix FlyingLotus1983 modbus lib:
https://github.com/FlyingLotus1983/arduino-modbus-slave
with this one ?

You can not use this libraries together.

**Comment by behroz123** [comment]
#include <modbus.h>
#include <modbusDevice.h>
#include <modbusRegBank.h>
#include <modbusSlave.h>
#define SLAVE_ID 1
#define CTRL_PIN 8
#define BAUDRATE 9600
Modbus slave(Serial1, SLAVE_ID, CTRL_PIN);

/* PINS
Add more registers if needed
Digital input pins 2,3,4,5,6,7
Digital output pins 8,9,12,13
Analog output pins 10,11 (PWM)
Analog input pins 0,1,2,3,4,5
*/

modbusDevice regBank;
modbusSlave slave;

int AI0,AI1,AI2,AI3,AI4,AI5;
 slave.cbVector[CB_WRITE_COIL] = writeDigitlOut;
    slave.cbVector[CB_READ_COILS] = readDigitalIn;
    slave.cbVector[CB_READ_REGISTERS] = readAnalogIn;
Serial1.begin( BAUDRATE );
slave.begin( BAUDRATE );


void setup()
{
  regBank.setId(1); ///Set Slave ID


//Add Digital Input registers
  regBank.add(10002);
  regBank.add(10003);
  regBank.add(10004);
  regBank.add(10005);
  regBank.add(10006);
  regBank.add(10007);
// Add Digital Output registers
  regBank.add(8);
  regBank.add(9);
  regBank.add(12);
  regBank.add(13);
//Analog input registers
  regBank.add(30001);
  regBank.add(30002);
  regBank.add(30003);
  regBank.add(30004);
  regBank.add(30005);
  regBank.add(30006);
//Analog Output registers
  regBank.add(40010);
  regBank.add(40011);

  slave._device = &regBank;
  slave.setBaud(9600);

  pinMode(2,INPUT);
  pinMode(3,INPUT);
  pinMode(4,INPUT);
  pinMode(5,INPUT);
  pinMode(6,INPUT);
  pinMode(7,INPUT);
  pinMode(8,OUTPUT);
  pinMode(9,OUTPUT);
  pinMode(12,OUTPUT);
  pinMode(13,OUTPUT);

}
void loop(){

  while(1){
  //Digital Input
    byte DI2 = digitalRead(2);
    if (DI2 >= 1)regBank.set(10002,1);
    if (DI2 <= 0)regBank.set(10002,0);
    byte DI3 = digitalRead(3);
    if (DI3 >= 1)regBank.set(10003,1);
    if (DI3 <= 0)regBank.set(10003,0);
    byte DI4 = digitalRead(4);
    if (DI4 >= 1)regBank.set(10004,1);
    if (DI4 <= 0)regBank.set(10004,0);
    byte DI5 = digitalRead(5);
    if (DI5 >= 1)regBank.set(10005,1);
    if (DI5 <= 0)regBank.set(10005,0);
    byte DI6 = digitalRead(6);
    if (DI6 >= 1)regBank.set(10006,1);
    if (DI6 <= 0)regBank.set(10006,0);
    byte DI7 = digitalRead(7);
    if (DI7 >= 1)regBank.set(10007,1);
    if (DI7 <= 0)regBank.set(10007,0);

  //Digital output
    int DO8 = regBank.get(8);
      if (DO8 <= 0 && digitalRead(8) == HIGH)digitalWrite(8,LOW);
      if (DO8 >= 1 && digitalRead(8) == LOW)digitalWrite(8,HIGH);
    int DO9 = regBank.get(9);
      if (DO9 <= 0 && digitalRead(9) == HIGH)digitalWrite(9,LOW);
      if (DO9 >= 1 && digitalRead(9) == LOW)digitalWrite(9,HIGH);
    int DO12 = regBank.get(12);
      if (DO12 <= 0 && digitalRead(12) == HIGH)digitalWrite(12,LOW);
      if (DO12 >= 1 && digitalRead(12) == LOW)digitalWrite(12,HIGH);
    int DO13 = regBank.get(13);
      if (DO13 <= 0 && digitalRead(13) == HIGH)digitalWrite(13,LOW);
      if (DO13 >= 1 && digitalRead(13) == LOW)digitalWrite(13,HIGH);

  //Analog input  ***READ Twice deliberately
    AI0 = analogRead(0);
    delay(10);
    AI0 = analogRead(0);
    regBank.set(30001, (word) AI0);
    delay(10);

    AI1 = analogRead(1);
    delay(10);
    AI1 = analogRead(1);
    regBank.set(30002, (word) AI1);
    delay(10);

    AI2 = analogRead(2);
    delay(10);
    AI2 = analogRead(2);
    regBank.set(30003, (word) AI2);
    delay(10);

    AI3 = analogRead(3);
    delay(10);
    AI3 = analogRead(3);
    regBank.set(30004, (word) AI3);
    delay(10);

    AI4 = analogRead(4);
    delay(10);
    AI4 = analogRead(4);
    regBank.set(30005, (word) AI4);
    delay(10);

    AI5 = analogRead(5);
    delay(10);
    AI5 = analogRead(5);
    regBank.set(30006, (word) AI5);
    delay(10);

  //Analog output
    word AO10 = regBank.get(40010);
    analogWrite(10,AO10);
    delay(10);
    word AO11 = regBank.get(40011);
    analogWrite(11,AO11);
    delay(10);

  slave.run();
  }
}





Arduino: 1.8.4 (Windows 8.1), Board: "Arduino/Genuino Mega or Mega 2560,
ATmega2560 (Mega 2560)"

sketch_oct05a:8: error: 'Modbus' does not name a type

 Modbus slave(Serial1, SLAVE_ID, CTRL_PIN);

 ^

sketch_oct05a:22: error: 'slave' does not name a type

  slave.cbVector[CB_WRITE_COIL] = writeDigitlOut;

  ^

sketch_oct05a:23: error: 'slave' does not name a type

     slave.cbVector[CB_READ_COILS] = readDigitalIn;

     ^

sketch_oct05a:24: error: 'slave' does not name a type

     slave.cbVector[CB_READ_REGISTERS] = readAnalogIn;

     ^

sketch_oct05a:25: error: 'Serial1' does not name a type

 Serial1.begin( BAUDRATE );

 ^

sketch_oct05a:26: error: 'slave' does not name a type

 slave.begin( BAUDRATE );

 ^

exit status 1
'Modbus' does not name a type

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by behroz123** [comment]
Arduino: 1.8.4 (Windows 8.1), Board: "Arduino/Genuino Mega or Mega 2560,
ATmega2560 (Mega 2560)"

sketch_oct05a:8: error: 'Modbus' does not name a type

 Modbus slave(Serial1, SLAVE_ID, CTRL_PIN);

 ^

sketch_oct05a:22: error: 'slave' does not name a type

  slave.cbVector[CB_WRITE_COIL] = writeDigitlOut;

  ^

sketch_oct05a:23: error: 'slave' does not name a type

     slave.cbVector[CB_READ_COILS] = readDigitalIn;

     ^

sketch_oct05a:24: error: 'slave' does not name a type

     slave.cbVector[CB_READ_REGISTERS] = readAnalogIn;

     ^

sketch_oct05a:25: error: 'Serial1' does not name a type

 Serial1.begin( BAUDRATE );

 ^

sketch_oct05a:26: error: 'slave' does not name a type

 slave.begin( BAUDRATE );

 ^

exit status 1
'Modbus' does not name a type

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by behroz123** [comment]
please source code send me
thanks

**Comment by behroz123** [comment]
؟

**Comment by behroz123** [comment]
Arduino: 1.8.4 (Windows 8.1), Board: "Arduino/Genuino Mega or Mega 2560,
ATmega2560 (Mega 2560)"

sketch_oct05a:21: error: 'slave' does not name a type

  slave.cbVector[CB_WRITE_COIL] = writeDigitlOut;

  ^

sketch_oct05a:22: error: 'slave' does not name a type

     slave.cbVector[CB_READ_COILS] = readDigitalIn;

     ^

sketch_oct05a:23: error: 'slave' does not name a type

     slave.cbVector[CB_READ_REGISTERS] = readAnalogIn;

     ^

sketch_oct05a:24: error: 'Serial1' does not name a type

 Serial1.begin( BAUDRATE );

 ^

sketch_oct05a:25: error: 'slave' does not name a type

 slave.begin( BAUDRATE );

 ^

exit status 1
'slave' does not name a type

A library named arduino-modbus-slave-master already exists
The library "MODBUS library 0.01b" cannot be used.
Library names must contain only basic letters and numbers.
(ASCII only and no spaces, and it cannot start with a number)
Specified folder/zip file does not contain a valid library

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by behroz123** [comment]
please send me source project mudbus with serial1 or 2
thanks

**Comment by yaacov** [comment]
> please send me source project mudbus with serial1 or 2

you have all you need, please read above comments.

**Comment by behroz123** [comment]
library rs 485 with serial 1 or 2 send me

**Comment by yaacov** [comment]
> library rs 485 with serial 1 or 2 send me

https://www.arduino.cc/en/Tutorial/MultiSerialMega

But your code can not work, because you are mixing libraries:

This libraries:  
```
#include <modbus.h> 
#include <modbusDevice.h> 
#include <modbusRegBank.h> 
```
Can not work in the same program with:
```
#include <modbusSlave.h>
```

**Comment by behroz123** [comment]
please library modbus rs 485 with serial 1 or 2 send me
thanks

**Comment by behroz123** [comment]
please

**Pull request closed without merging**
