### PR TITLE
Multiple issues solved - compatible API

### PR DESCRIPTION
**Pull request by falahati**
Hey,

This is an almost complete rewrite of the communication part of the code as well as some minor and some major refactoring along with other new features. However, it still should be compatible with older versions and therefore safe to update to. I really liked to change parts of API but that would mean that you have to release a new version indicating the change in API.

Should address #33, #32 and #25.

### CODE REVIEW

**Comment by yaacov** [comment]
Wow, that's a lot of changes :+1: it will take me time to read it all ...

**Comment by yaacov** [comment]
If you can break it up to smaller PR's that address specific issue, it will be easier to merge, because I will not have to read so much code at once :heart:

**Comment by yaacov** [comment]
@falahati 
If you do not have the time to split it to several small PR's I will merge it as is, but it will be much nicer to have smaller PR's that are easy to follow without spending too much time reading.

For example:
-   Adding the default values and constants, deserve it's own PR.
-   Refactoring out the  `executeCallback` method, deserve it's own PR.
-   Changing var names ...
-   Updating remarks / docs ...
-  ...

**Comment by falahati** [comment]
It's not the first time I am doing something like that with open source projects. So believe when I say I know this isn't the way to push this much changes. xD Sorry about that. Totally my bad. Can't help it I suppose.

That being said, breaking it up now, is almost impossible due to the fact that the changes are not actually local that can be split. I just started refactoring the code from the top and when I reached the end of the file it was almost a complete rewrite and I had to commit them all at once. Breaking it up means that I need to go through the whole process again (this time with a plan xD) while before each commit making sure that the existing code works well with modified parts. This is more work than the first time.

I thought of keeping it as a complete separate fork and also do the API changes I wanted to do but didn't, since as a new package backward compatibility wasn't an issue. But I already talked about these changes and promised a PR; so I had to.

Still, if you think it is impossible to read this much change; I am happy to keep it as a separate fork of your library. No pressure.

PS: I suggest reading and reviewing it at once and alone instead of comparing it with older source and see if it all makes sense. I tested this new version with `AltSoftSerial` and two Windows RS485 master simulator; so you might want to test it with something else like `SoftwareSerial` or the hardware `Serial`. even tho it should work. I also suggested a PR for  `AltSoftSerial` to solve the problem in regard to not implementing the `availableForWrite()` method that they should have.

**Comment by yaacov** [comment]
> Breaking it up means that I need to go through the whole process again (this time with a plan xD)

np, merging :-)

Have fun in the weekend :beers: :cake:

**Comment by dgoo2308** [comment]
@falahati was #32 solved?

I have a project and noticed broadcast did not work, i reviewed the code a bit and found that the callbacks in case of a broadcast write are not called.

```c
/**
 * Executes a callback.
 *
 * @return The status code representing the outcome of this operation.
 */
uint8_t Modbus::executeCallback(uint8_t slaveAddress, uint8_t callbackIndex, uint16_t address, uint16_t length)
{
    // Search for the correct slave to execute callback on.
    for (uint8_t i = 0; i < _numberOfSlaves; ++i)
    {
        if (_slaves[i].getUnitAddress() == slaveAddress)
        {
            // If the callback exist execute it, otherwise return that this is an illegal function.
            if (_slaves[i].cbVector[callbackIndex])
            {
                return _slaves[i].cbVector[callbackIndex](Modbus::readFunctionCode(), address, length);
            }
            else
            {
                return STATUS_ILLEGAL_FUNCTION;
            }
        }
    }
    return STATUS_ILLEGAL_FUNCTION;
}

```

I'll try with this:

```
diff --git a/src/ModbusSlave.cpp b/src/ModbusSlave.cpp
index b4cb97b..38c10f9 100644
--- a/src/ModbusSlave.cpp
+++ b/src/ModbusSlave.cpp
@@ -809,8 +809,30 @@ uint8_t Modbus::executeCallback(uint8_t slaveAddress, uint8_t callbackIndex, uin
                 return STATUS_ILLEGAL_FUNCTION;
             }
         }
+        else if (slaveAddress==MODBUS_BROADCAST_ADDRESS)
+        {
+            switch (Modbus::readFunctionCode())
+            {
+                //broadcast is defined for all writes, so write, don't care return value
+                case FC_WRITE_COIL:
+                case FC_WRITE_REGISTER:
+                case FC_WRITE_MULTIPLE_REGISTERS:
+                case FC_WRITE_MULTIPLE_COILS:
+                    uint8_t ret=_slaves[i].cbVector[callbackIndex](Modbus::readFunctionCode(), address, length);
+                    if (ret) ret=0;
+                default: break;
+            }
+        }
     }
-    return STATUS_ILLEGAL_FUNCTION;
+    if ((slaveAddress==MODBUS_BROADCAST_ADDRESS ))
+    {
+        // if it ws a broadcast, return ok
+        return STATUS_OK;
+    }
+    else
+    {
+        return STATUS_ILLEGAL_FUNCTION;
+    } 
 }
 
 /**
```

**Comment by falahati** [comment]
@dgoo2308 Good catch; I initially needed this but it seems that since I changed my logic I forgot to check if broadcast works.

I will create a PR for this. Thanks for reporting the issue.

**Comment by falahati** [comment]
If it is possible for, please try this branch: https://github.com/falahati/ArduinoModbusSlave/tree/fix4

I already made a PR (#62), however since I don't currently have a hardware close to me, I did not test it on real hardware; I just checked to see if it compiles.

Thank you.

**Pull request merged**
